export interface Material {
  id: string;
  material: string;
  summary: string | null;
  applications: string | null;
  production_methods: string | null;
  key_properties: string | null;
  market_size: string | null;
  market_trends: string | null;
  major_producers: string | null;
  major_consumers: string | null;
  geopolitical_factors: string | null;
  regulatory_environment: string | null;
  technological_advancements: string | null;
  environmental_impact: string | null;
  recycling_and_substitution: string | null;
  price_history: string | null;
  price_volatility: number | null;
  trading_volume: string | null;
  exchange_listings: string | null;
  derivatives_market: string | null;
  market_sentiment: string | null;
  supply_and_demand_forecast: string | null;
  price_forecast: string | null;
  national_security_implications: string | null;
  defense_applications: string | null;
  stockpile_information: string | null;
  dual_use_technologies: string | null;
  import_export_restrictions: string | null;
  supply_chain_map: string | null;
  key_suppliers: string | null;
  transportation_logistics: string | null;
  processing: string | null;
  chokepoints: string | null;
  supply_chain_vulnerability_score: number | null;
  logistics_complexity_score: number | null;
  inventory_holding_risk_score: number | null;
  investment_thesis: string | null;
  opportunities: string | null;
  risks: string | null;
  mitigation_recommendations: string | null;
  strategic_importance_score: number | null;
  market_timing_score: number | null;
  industries: string | null;
  buyers: string | null;
  dealers: string | null;
  key_end_customers: string | string[] | null;
  end_market_sectors: string | string[] | null;
  data_sources: string | null;
  data_last_updated: string | null;
  data_confidence_score: string | null;
  price_reporting_sources: string | string[] | null;
}
